#!/bin/bash
#$ -S /bin/bash
#$ -N match
#$ -cwd
#$ -e log.match
#$ -o log.match
#$ -l h_vmem=16G
#$ -v ROSETTA_BIN
#$ -v ROSETTA_DB

$ROSETTA_BIN/match.default.linuxgccrelease -database $ROSETTA_DB -s 2jie_0001.pdb -match:lig_name LG1 -match:scaffold_active_site_residues positions.pos -match:geometric_constraint_file LG1.enzdes.csts -extra_res_fa LG1.params  -mute protocols.idealize -use_input_sc -ex1 -ex2 -euclid_bin_size 0.5 -euler_bin_size 5.0 -bump_tolerance 0.3
